name: Imperium CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Check out the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          echo "Moving to the project directory..."
          cd /HR-Managment-System
          echo "Installing dependencies..."
          npm install
          npm i eslint jest --save-dev

      # Step 4: Lint the code with ESLint
      - name: Lint with ESLint
        run: |
          echo "Linting code..."
          npx eslint . --fix

      # Step 5: Run Jest tests
      - name: Test with Jest
        run: |
          echo "Running tests..."
          npm test
